name: pager
channels:
- conda-forge
- defaults  
dependencies:
- beautifulsoup4
- cartopy
- cython
- decorator
- descartes
- docutils
- fiona
- flake8
- gdal
- h5py
- hypothesis
- impactutils
- jupyter
- mapio
# Need to restrict matplotlib to <2.0
# because of a change in how contour works
- matplotlib
- mock
- nose
- openpyxl
- openquake.engine
- pandas
- paramiko
- psutil
- pycrypto
- pyproj
- pytables
- python=3.5
- pytest
- pytest-cov
- pytest-mpl
- pyyaml
- rasterio
- rtree
- scipy
- shapely
- sqlalchemy
- sqlalchemy-utils
- xlrd
- xlwt

